### ISSUE TITLE
Panic on fresh sync up

### ISSUE THREAD

**Issue by ETeissonniere** [NodleCode/chain#21]
We pushed an upgrade to the network linked to #20 however fresh node synchronizing there seems to panic around block `131,140`

```
2020-04-03 01:31:55 Syncing  0.0 bps, target=#131682 (2 peers), best: #131319 (0xc251…e963), finalized #131072 (0xae65…2a78), ⬇ 99.5kiB/s ⬆ 2.0kiB/s
Hash: given=bbc736cd9484e3ea6a3697eb06900272093a63691bdb28bd4cad63058fb527e5, expected=0826fde67c866d994469a239880a92a8273957160bb7c7324f17e7c54ffa6745

====================

Version: 2.0.0-493097c-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:476
   2: std::panicking::begin_panic
   3: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules>::execute_block
   4: <nodle_chain_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<<pallet_indices::Module<nodle_chain_runtime::Runtime> as sp_runtime::traits::StaticLookup>::Source,nodle_chain_runtime::Call,sp_runtime::MultiSignature,(frame_system::CheckVersion<nodle_chain_runtime::Runtime>, frame_system::CheckGenesis<nodle_chain_runtime::Runtime>, frame_system::CheckEra<nodle_chain_runtime::Runtime>, frame_system::CheckNonce<nodle_chain_runtime::Runtime>, frame_system::CheckWeight<nodle_chain_runtime::Runtime>, pallet_transaction_payment::ChargeTransactionPayment<nodle_chain_runtime::Runtime>)>>>>::execute_block
   5: sp_api::runtime_decl_for_Core::execute_block_native_call_generator::{{closure}}
   6: std::panicking::try::do_call
   7: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
   8: std::thread::local::LocalKey<T>::with
   9: std::thread::local::LocalKey<T>::with
  10: sp_state_machine::StateMachine<B,H,N,Exec>::execute_aux
  11: <sc_client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
  12: <sc_client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  13: sp_api::runtime_decl_for_Core::execute_block_call_api_at
  14: sp_api::Core::execute_block
  15: <&sc_client::client::Client<B,E,Block,RA> as sp_consensus::block_import::BlockImport<Block>>::import_block
  16: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sp_consensus::block_import::BlockImport<Block>>::import_block
  17: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::block_import::BlockImport<Block>>::import_block
  18: sp_consensus::import_queue::import_single_block
  19: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  20: futures_util::future::future::chain::Chain<Fut1,Fut2,Data>::poll
  21: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  22: futures_executor::thread_pool::PoolState::work
  23: std::sys_common::backtrace::__rust_begin_short_backtrace
  24: std::panicking::try::do_call
  25: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  26: core::ops::function::FnOnce::call_once{{vtable.shim}}
  27: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
  28: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:80
  29: start_thread
  30: __clone


Thread 'import-queue-worker-0' panicked at 'Storage root must match that calculated.', <::std::macros::panic macros>:2

This is a bug. Please report it at:

	https://github.com/NodleCode/chain/issues

2020-04-03 01:31:55 Block prepare storage changes error:
Execution(RuntimePanicked("Storage root must match that calculated."))
```

**Comment by ETeissonniere** [comment]
It is possible to sync the chain with an older node and then upgrade to the new one. We are adding a third validator `regression-1` in an attempt to mitigate this solution without rebooting the network.
